name: CD
 
on:
  push:
    branches: [main]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Copy docker-compose.yml to remote server
        run: |
          echo "yCiJU2qXFC3eiA" > id_rsa
          chmod 600 id_rsa
          scp -i id_rsa -o StrictHostKeyChecking=no -C -c aes256-gcm@openssh.com docker-compose.yml root@$139.144.0.51:/home/app
          rm id_rsa

            
      - name: Log in to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from Docker Hub on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd app
            docker-compose pull

      - name: Start app on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd app
            docker-compose up -d

      - name: Log out from Docker Hub
        run: docker logout
